FROM postgres:12.1-alpine
#FROM postgres:12.1

#RUN chmod 777 /var/lib/postgresql/data/pg_hba.conf
#RUN chmod 777 /var/lib/postgresql/data/postgresql.conf
#RUN mv /var/lib/postgresql/data/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf.bak
#RUN mv /var/lib/postgresql/data/postgresql.conf /var/lib/postgresql/data/postgresql.conf.bak

#ADD pg_hba.conf /var/lib/postgresql/data/db-files/pg_hba.conf
#ADD postgresql.conf /var/lib/postgresql/data/db-files/postgresql.conf
