# Generated by Django 2.2.4 on 2019-11-19 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='accounts.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
