# Generated by Django 2.2.4 on 2019-11-14 11:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('receipt', 'Receipt'), ('businesscard', 'Business Card'), ('contract', 'Contract')], max_length=20, verbose_name='Document Type')),
                ('document_content', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='document', to='accounts.Tenant')),
            ],
            options={
                'db_table': 'next_documents',
            },
        ),
    ]
