# Generated by Django 2.2.4 on 2019-11-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('next', '0002_category_data_field_membership_payment_userclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('professional', 'Professional')], max_length=20, verbose_name='Plan Type')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
