# Generated by Django 2.2.4 on 2019-11-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next', '0003_auto_20191119_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantProfile',
        ),
    ]
